### ISSUE TITLE
Add Support for GitHub and other VCS integrations

### ISSUE THREAD

**Issue by away168** [env0/env0-migration-tool#15] opened 2024-01-18 20:56 UTC
new environments are only only configured with "generic git"

ability to determine which git provider and configure the vcs integration will help save time later trying to update each environment

**Comment by sagilaufer1992** [comment] 2024-01-19 09:43
Duplicate of #9 
@away168 if needed, please update the referenced issue, to include more case or widen the scope

**Closed by sagilaufer1992** 2024-01-19 09:43 UTC
